'use strict';

const I18N_MESSAGES = {
  es:{
    'language.label':'Idioma','language.es':'Español','language.it':'Italiano','language.en':'English','common.phase':'FASE','builder.logicFormula':'Fórmula lógica','builder.wholeRule':'Regla completa',
    'login.subtitle':'Piloto Messina · PoC de vulnerabilidad energética','login.demo':'Entorno de demostración','login.synthetic':'Datos sintéticos · sin autenticación real','login.user':'Evaluador','login.userPlaceholder':'Nombre o código de evaluador','login.role':'Rol de demostración','login.password':'Contraseña','login.passwordPlaceholder':'Contraseña de acceso','login.enter':'Entrar →',
    'role.methodology':'Diseño metodológico','role.expert':'Persona experta','role.facilitator':'Facilitación del consenso','role.observer':'Observación y auditoría',
    'top.activeProfile':'Perfil activo:','top.user':'Usuario:','top.change':'Cambiar','top.reference':'Mostrar etiquetas de referencia',
    'workflow.profile-builder.short':'Perfiles','workflow.profile-builder.title':'Construcción de perfiles','workflow.profile-builder.state':'Prototipo disponible','workflow.profile-builder.description':'Combinar indicadores en perfiles, definir su activación y publicar las variables que ponderarán los expertos.',
    'workflow.expert-evaluation.short':'Expertos','workflow.expert-evaluation.title':'Evaluación experta individual','workflow.expert-evaluation.state':'Funcional',
    'workflow.expert-consensus.short':'Consenso','workflow.expert-consensus.title':'Consenso entre personas expertas','workflow.expert-consensus.state':'Prototipo disponible',
    'workflow.community-input.short':'Usuarios','workflow.community-input.title':'Preferencias de participantes','workflow.community-input.state':'Roadmap',
    'workflow.community-consensus.short':'Asamblea','workflow.community-consensus.title':'Consenso comunitario','workflow.community-consensus.state':'Roadmap',
    'workflow.benefits-expert.short':'Beneficios','workflow.benefits-expert.title':'Criterios de reparto expertos','workflow.benefits-expert.state':'Roadmap',
    'workflow.benefits-community.short':'Validación','workflow.benefits-community.title':'Validación del reparto','workflow.benefits-community.state':'Roadmap',
    'builder.title':'Construcción de perfiles','builder.subtitle':'Indicadores ya calculados → activación → perfil → ponderación experta','builder.design':'Diseño del perfil','builder.method':'Información metodológica','builder.methodHint':'Fuentes, versión, cautelas y trazabilidad se consultan aquí sin ocupar el espacio de edición.','builder.identity':'1 · Identidad','builder.name':'Nombre','builder.short':'Nombre corto','builder.color':'Color','builder.question':'Pregunta experta','builder.description':'Descripción','builder.composition':'2 · Composición','builder.primary':'Indicadores primarios','builder.secondary':'Indicadores secundarios','builder.pending':'Pendientes','builder.activation':'3 · Regla activadora','builder.activationHelp':'Cada condición devuelve TRUE cuando el indicador cumple su propio criterio. Aquí decides cómo combinar esas condiciones.','builder.trueCondition':'cumple su criterio → TRUE','builder.addCondition':'＋ Añadir condición','builder.replaceCondition':'Cambiar indicador','builder.reading':'Lectura','builder.variables':'4 · Variables que ponderarán los expertos','builder.weightsHint':'El porcentaje mostrado es solo el punto de partida; se modifica en la fase experta.','builder.addVariable':'＋ Añadir variable','builder.initial':'inicial','builder.remove':'Quitar','builder.preview':'5 · Vista previa','builder.previewHint':'Activación y score con hogares sintéticos','builder.active':'ACTIVO','builder.inactive':'No activo','builder.validation':'6 · Validación y publicación','builder.restore':'Restaurar guardado','builder.export':'↓ Exportar JSON','builder.import':'↑ Importar JSON','builder.saveDraft':'Guardar DRAFT','builder.review':'Enviar a REVIEW','builder.publish':'Publicar para expertos','builder.newProfile':'＋ Nuevo perfil','builder.viewOnly':'Vista de consulta. Usa el rol Diseño metodológico para editar.','builder.valid':'Regla activadora y priorización válidas.','builder.source':'Fuente metodológica','builder.activationRationale':'Justificación de la activación','builder.cautions':'Cautelas y decisiones pendientes','builder.version':'Estado metodológico','builder.profiles':'perfiles','builder.published':'publicados','builder.primaryRole':'Primario','builder.secondaryRole':'Secundario','builder.addedRole':'Añadido',
    'profiles.P1.name':'Vulnerabilidad económica estructural','profiles.P1.short':'Económica','profiles.P2.name':'Vulnerabilidad por condiciones de la vivienda','profiles.P2.short':'Vivienda','profiles.P3.name':'Pobreza energética oculta','profiles.P3.short':'P. oculta','profiles.P4.name':'Fragilidad del hogar y dependencia eléctrica','profiles.P4.short':'Fragilidad','profiles.P5.name':'Vulnerabilidad territorial y de acceso','profiles.P5.short':'Territorial','profiles.P6.name':'Vulnerabilidad socio-comunitaria','profiles.P6.short':'Socio-com.',
  },
  it:{
    'language.label':'Lingua','language.es':'Español','language.it':'Italiano','language.en':'English','common.phase':'FASE','builder.logicFormula':'Formula logica','builder.wholeRule':'Regola completa',
    'login.subtitle':'Pilota Messina · PoC sulla vulnerabilità energetica','login.demo':'Ambiente dimostrativo','login.synthetic':'Dati sintetici · nessuna autenticazione reale','login.user':'Valutatore','login.userPlaceholder':'Nome o codice del valutatore','login.role':'Ruolo dimostrativo','login.password':'Password','login.passwordPlaceholder':'Password di accesso','login.enter':'Accedi →',
    'role.methodology':'Progettazione metodologica','role.expert':'Persona esperta','role.facilitator':'Facilitazione del consenso','role.observer':'Osservazione e audit',
    'top.activeProfile':'Profilo attivo:','top.user':'Utente:','top.change':'Cambia','top.reference':'Mostra etichette di riferimento',
    'workflow.profile-builder.short':'Profili','workflow.profile-builder.title':'Costruzione dei profili','workflow.profile-builder.state':'Prototipo disponibile','workflow.profile-builder.description':'Combinare gli indicatori nei profili, definirne l’attivazione e pubblicare le variabili che gli esperti pondereranno.',
    'workflow.expert-evaluation.short':'Esperti','workflow.expert-evaluation.title':'Valutazione individuale degli esperti','workflow.expert-evaluation.state':'Funzionale',
    'workflow.expert-consensus.short':'Consenso','workflow.expert-consensus.title':'Consenso tra esperti','workflow.expert-consensus.state':'Prototipo disponibile',
    'workflow.community-input.short':'Utenti','workflow.community-input.title':'Preferenze dei partecipanti','workflow.community-input.state':'Roadmap',
    'workflow.community-consensus.short':'Assemblea','workflow.community-consensus.title':'Consenso comunitario','workflow.community-consensus.state':'Roadmap',
    'workflow.benefits-expert.short':'Benefici','workflow.benefits-expert.title':'Criteri esperti di distribuzione','workflow.benefits-expert.state':'Roadmap',
    'workflow.benefits-community.short':'Convalida','workflow.benefits-community.title':'Convalida della distribuzione','workflow.benefits-community.state':'Roadmap',
    'builder.title':'Costruzione dei profili','builder.subtitle':'Indicatori calcolati → attivazione → profilo → ponderazione esperta','builder.design':'Progettazione del profilo','builder.method':'Informazioni metodologiche','builder.methodHint':'Fonti, versione, cautele e tracciabilità sono consultabili qui senza occupare lo spazio di modifica.','builder.identity':'1 · Identità','builder.name':'Nome','builder.short':'Nome breve','builder.color':'Colore','builder.question':'Domanda per gli esperti','builder.description':'Descrizione','builder.composition':'2 · Composizione','builder.primary':'Indicatori primari','builder.secondary':'Indicatori secondari','builder.pending':'In attesa','builder.activation':'3 · Regola di attivazione','builder.activationHelp':'Ogni condizione restituisce TRUE quando l’indicatore soddisfa il proprio criterio. Qui si decide come combinare le condizioni.','builder.trueCondition':'soddisfa il criterio → TRUE','builder.addCondition':'＋ Aggiungi condizione','builder.replaceCondition':'Cambia indicatore','builder.reading':'Lettura','builder.variables':'4 · Variabili ponderate dagli esperti','builder.weightsHint':'La percentuale mostrata è solo il punto di partenza; viene modificata nella fase esperta.','builder.addVariable':'＋ Aggiungi variabile','builder.initial':'iniziale','builder.remove':'Rimuovi','builder.preview':'5 · Anteprima','builder.previewHint':'Attivazione e punteggio con famiglie sintetiche','builder.active':'ATTIVO','builder.inactive':'Non attivo','builder.validation':'6 · Validazione e pubblicazione','builder.restore':'Ripristina salvato','builder.export':'↓ Esporta JSON','builder.import':'↑ Importa JSON','builder.saveDraft':'Salva DRAFT','builder.review':'Invia a REVIEW','builder.publish':'Pubblica per gli esperti','builder.newProfile':'＋ Nuovo profilo','builder.viewOnly':'Vista di sola lettura. Usa il ruolo Progettazione metodologica per modificare.','builder.valid':'Regola di attivazione e prioritizzazione valide.','builder.source':'Fonte metodologica','builder.activationRationale':'Motivazione dell’attivazione','builder.cautions':'Cautele e decisioni aperte','builder.version':'Stato metodologico','builder.profiles':'profili','builder.published':'pubblicati','builder.primaryRole':'Primario','builder.secondaryRole':'Secondario','builder.addedRole':'Aggiunto',
    'profiles.P1.name':'Vulnerabilità economica strutturale','profiles.P1.short':'Economica','profiles.P2.name':'Vulnerabilità dovuta alle condizioni abitative','profiles.P2.short':'Abitazione','profiles.P3.name':'Povertà energetica nascosta','profiles.P3.short':'Povertà nascosta','profiles.P4.name':'Fragilità familiare e dipendenza elettrica','profiles.P4.short':'Fragilità','profiles.P5.name':'Vulnerabilità territoriale e di accesso','profiles.P5.short':'Territoriale','profiles.P6.name':'Vulnerabilità socio-comunitaria','profiles.P6.short':'Socio-com.',
  },
  en:{
    'language.label':'Language','language.es':'Español','language.it':'Italiano','language.en':'English','common.phase':'PHASE','builder.logicFormula':'Logical formula','builder.wholeRule':'Whole rule',
    'login.subtitle':'Messina pilot · Energy vulnerability PoC','login.demo':'Demonstration environment','login.synthetic':'Synthetic data · no real authentication','login.user':'Evaluator','login.userPlaceholder':'Evaluator name or code','login.role':'Demo role','login.password':'Password','login.passwordPlaceholder':'Access password','login.enter':'Enter →',
    'role.methodology':'Methodology design','role.expert':'Expert','role.facilitator':'Consensus facilitation','role.observer':'Observation and audit',
    'top.activeProfile':'Active profile:','top.user':'User:','top.change':'Change','top.reference':'Show reference labels',
    'workflow.profile-builder.short':'Profiles','workflow.profile-builder.title':'Profile construction','workflow.profile-builder.state':'Prototype available','workflow.profile-builder.description':'Combine indicators into profiles, define activation and publish the variables experts will weight.',
    'workflow.expert-evaluation.short':'Experts','workflow.expert-evaluation.title':'Individual expert assessment','workflow.expert-evaluation.state':'Functional',
    'workflow.expert-consensus.short':'Consensus','workflow.expert-consensus.title':'Expert consensus','workflow.expert-consensus.state':'Prototype available',
    'workflow.community-input.short':'Users','workflow.community-input.title':'Participant preferences','workflow.community-input.state':'Roadmap',
    'workflow.community-consensus.short':'Assembly','workflow.community-consensus.title':'Community consensus','workflow.community-consensus.state':'Roadmap',
    'workflow.benefits-expert.short':'Benefits','workflow.benefits-expert.title':'Expert allocation criteria','workflow.benefits-expert.state':'Roadmap',
    'workflow.benefits-community.short':'Validation','workflow.benefits-community.title':'Allocation validation','workflow.benefits-community.state':'Roadmap',
    'builder.title':'Profile construction','builder.subtitle':'Calculated indicators → activation → profile → expert weighting','builder.design':'Profile design','builder.method':'Methodology information','builder.methodHint':'Sources, version, cautions and traceability live here without taking up editing space.','builder.identity':'1 · Identity','builder.name':'Name','builder.short':'Short name','builder.color':'Colour','builder.question':'Expert question','builder.description':'Description','builder.composition':'2 · Composition','builder.primary':'Primary indicators','builder.secondary':'Secondary indicators','builder.pending':'Pending','builder.activation':'3 · Activation rule','builder.activationHelp':'Each condition returns TRUE when the indicator meets its own criterion. Here you decide how to combine those conditions.','builder.trueCondition':'meets its criterion → TRUE','builder.addCondition':'＋ Add condition','builder.replaceCondition':'Change indicator','builder.reading':'Reading','builder.variables':'4 · Variables weighted by experts','builder.weightsHint':'The displayed percentage is only the starting point; it is changed during the expert phase.','builder.addVariable':'＋ Add variable','builder.initial':'initial','builder.remove':'Remove','builder.preview':'5 · Preview','builder.previewHint':'Activation and score using synthetic households','builder.active':'ACTIVE','builder.inactive':'Inactive','builder.validation':'6 · Validation and publishing','builder.restore':'Restore saved','builder.export':'↓ Export JSON','builder.import':'↑ Import JSON','builder.saveDraft':'Save DRAFT','builder.review':'Send to REVIEW','builder.publish':'Publish for experts','builder.newProfile':'＋ New profile','builder.viewOnly':'Read-only view. Use the Methodology design role to edit.','builder.valid':'Activation rule and prioritisation are valid.','builder.source':'Methodology source','builder.activationRationale':'Activation rationale','builder.cautions':'Cautions and open decisions','builder.version':'Methodology status','builder.profiles':'profiles','builder.published':'published','builder.primaryRole':'Primary','builder.secondaryRole':'Secondary','builder.addedRole':'Added',
    'profiles.P1.name':'Structural economic vulnerability','profiles.P1.short':'Economic','profiles.P2.name':'Housing-condition vulnerability','profiles.P2.short':'Housing','profiles.P3.name':'Hidden energy poverty','profiles.P3.short':'Hidden poverty','profiles.P4.name':'Household fragility and electricity dependence','profiles.P4.short':'Fragility','profiles.P5.name':'Territorial and access vulnerability','profiles.P5.short':'Territorial','profiles.P6.name':'Socio-community vulnerability','profiles.P6.short':'Socio-community',
  },
};

const I18N_INDICATORS = {
  es:{
    I1:['Renta neta equivalente','< {renta_riesgo} €/mes → TRUE'],I2:['Bajo el umbral de pobreza','Renta < {pobreza} €/mes → TRUE'],I3:['Carga energética','> {carga}% → TRUE'],I4:['Impago o corte','Algún episodio en 12 meses → TRUE'],I5:['Consumo eléctrico','< {infra_elec} kWh → TRUE'],I6:['Consumo no eléctrico','< {infra_gas} kWh → TRUE'],I7:['Perfil horario','Patrón rígido → TRUE'],I8:['Pobreza energética oculta','Infraconsumo forzado detectado → TRUE'],I9:['Habitabilidad','Pobre o crítica → TRUE'],I10:['Sistemas energéticos','Deficientes u obsoletos → TRUE'],I11:['Acceso a ayudas','Ayuda social o energética reconocida → TRUE'],I12:['Microcrédito','Sin acceso → TRUE'],I13:['Capacidad energética y digital','Capacidad insuficiente → TRUE'],I14:['Participación digital comunitaria','Participación digital baja → TRUE'],I15:['Personas dependientes','≥ 1 persona dependiente → TRUE'],I16:['Dependencia funcional','Dependencia reconocida → TRUE'],I17:['Dependencia eléctrica o crónica','Necesidad eléctrica relevante → TRUE'],I18:['Índice territorial','> {territorial} → TRUE'],I19:['Acceso a servicios','> {acceso} min → TRUE'],I20:['Temperatura percibida','Malestar térmico declarado → TRUE'],I21:['Ahorros líquidos','< {ahorros} mes → TRUE'],I22:['Red de apoyo social','Débil o aislamiento → TRUE'],I23:['Participación comunitaria','Escasa o nula → TRUE'],I24:['Estigmatización','Moderada o severa → TRUE'],I25:['Estabilidad residencial','< {estabilidad} años → TRUE'],
  },
  it:{
    I1:['Reddito netto equivalente','< {renta_riesgo} €/mese → TRUE'],I2:['Sotto la soglia di povertà','Reddito < {pobreza} €/mese → TRUE'],I3:['Incidenza della spesa energetica','> {carga}% → TRUE'],I4:['Mancato pagamento o interruzione','Almeno un episodio in 12 mesi → TRUE'],I5:['Consumo elettrico','< {infra_elec} kWh → TRUE'],I6:['Consumo non elettrico','< {infra_gas} kWh → TRUE'],I7:['Profilo orario','Schema rigido → TRUE'],I8:['Povertà energetica nascosta','Sottoconsumo forzato rilevato → TRUE'],I9:['Abitabilità','Scarsa o critica → TRUE'],I10:['Sistemi energetici','Inadeguati o obsoleti → TRUE'],I11:['Accesso agli aiuti','Sostegno sociale o energetico riconosciuto → TRUE'],I12:['Microcredito','Nessun accesso → TRUE'],I13:['Capacità energetica e digitale','Capacità insufficiente → TRUE'],I14:['Partecipazione digitale comunitaria','Bassa partecipazione digitale → TRUE'],I15:['Persone dipendenti','≥ 1 persona dipendente → TRUE'],I16:['Dipendenza funzionale','Dipendenza riconosciuta → TRUE'],I17:['Dipendenza elettrica o patologia cronica','Fabbisogno elettrico rilevante → TRUE'],I18:['Indice territoriale','> {territorial} → TRUE'],I19:['Accesso ai servizi','> {acceso} min → TRUE'],I20:['Temperatura percepita','Disagio termico dichiarato → TRUE'],I21:['Risparmi liquidi','< {ahorros} mese → TRUE'],I22:['Rete di sostegno sociale','Debole o isolamento → TRUE'],I23:['Partecipazione comunitaria','Scarsa o nulla → TRUE'],I24:['Stigmatizzazione','Moderata o grave → TRUE'],I25:['Stabilità abitativa','< {estabilidad} anni → TRUE'],
  },
  en:{
    I1:['Equivalent net income','< {renta_riesgo} €/month → TRUE'],I2:['Below the poverty threshold','Income < {pobreza} €/month → TRUE'],I3:['Household energy burden','> {carga}% → TRUE'],I4:['Non-payment or supply interruption','At least one episode in 12 months → TRUE'],I5:['Electricity consumption','< {infra_elec} kWh → TRUE'],I6:['Non-electric energy consumption','< {infra_gas} kWh → TRUE'],I7:['Time-of-use profile','Rigid pattern → TRUE'],I8:['Hidden energy poverty','Forced underconsumption detected → TRUE'],I9:['Housing habitability','Poor or critical → TRUE'],I10:['Energy systems','Inadequate or obsolete → TRUE'],I11:['Access to assistance','Recognised social or energy support → TRUE'],I12:['Microcredit','No access → TRUE'],I13:['Energy and digital capability','Insufficient capability → TRUE'],I14:['Community digital participation','Low digital participation → TRUE'],I15:['Dependent household members','≥ 1 dependent person → TRUE'],I16:['Functional dependency','Recognised dependency → TRUE'],I17:['Electric or chronic dependency','Relevant electricity need → TRUE'],I18:['Territorial index','> {territorial} → TRUE'],I19:['Access to services','> {acceso} min → TRUE'],I20:['Perceived temperature','Reported thermal discomfort → TRUE'],I21:['Liquid savings','< {ahorros} month → TRUE'],I22:['Social support network','Weak support or isolation → TRUE'],I23:['Community participation','Low or none → TRUE'],I24:['Stigmatisation','Moderate or severe → TRUE'],I25:['Residential stability','< {estabilidad} years → TRUE'],
  },
};

const I18N_PROFILE_CONTENT = {
  it:{
    P1:{description:'Risorse strutturalmente insufficienti e pressione dei costi energetici, aggravate da insolvenze e bassa resilienza.',question:'Il nucleo presenta vulnerabilità economica strutturale?',rationale:'Si attiva in caso di povertà relativa o quando un reddito insufficiente coincide con un elevato onere energetico o un mancato pagamento. I11, I12, I21, I22 e I25 modulano la priorità.',cautions:['I1 e I2 sono correlati; il peso iniziale di I2 è zero per evitare un doppio conteggio prima della revisione degli esperti.','I22 è incluso come fattore complementare di resilienza con peso iniziale zero.']},
    P2:{description:'Vulnerabilità causata principalmente dalle condizioni fisiche, termiche o tecniche dell’abitazione.',question:'Il nucleo presenta vulnerabilità dovuta alle condizioni abitative?',rationale:'Si attiva quando l’abitabilità o i sistemi energetici presentano un rischio; consumi e disagio forniscono il contesto.',cautions:[]},
    P3:{description:'Sottoconsumo involontario non spiegato da un’abitazione efficiente e associato a vincoli economici.',question:'Il nucleo presenta povertà energetica nascosta?',rationale:'Richiede contemporaneamente un segnale di sottoconsumo, condizioni che escludano l’efficienza come spiegazione e un vincolo economico. I4 rafforza la priorità.',cautions:['I8 rimane un’approssimazione dimostrativa; il valore di riferimento deve essere adeguato a nucleo, abitazione e clima.']},
    P4:{description:'Fabbisogni energetici critici associati a dipendenza, mobilità ridotta, salute o dispositivi elettrici.',question:'Il nucleo presenta fragilità o dipendenza elettrica?',rationale:'Si attiva quando è presente almeno un segnale primario di fragilità. Il reddito non è un requisito di accesso.',cautions:['La continuità dell’alimentazione elettrica richiede una tutela specifica oltre al punteggio ponderato.']},
    P5:{description:'Svantaggio territoriale o barriere effettive nell’accesso a infrastrutture, servizi e meccanismi di protezione.',question:'Il nucleo presenta vulnerabilità territoriale o di accesso?',rationale:'Si attiva per rischio territoriale o barriere effettive di accesso; sostegno e partecipazione modulano la priorità.',cautions:['I19 compare in D1.5 e nella proposta dei profili, ma è ritirato nel catalogo V3.0. Viene mantenuto temporaneamente per tracciabilità fino alla definizione di un sostituto.']},
    P6:{description:'Debolezza del sostegno sociale, dell’integrazione comunitaria e della capacità effettiva di partecipare o accedere agli aiuti.',question:'Il nucleo presenta vulnerabilità socio-comunitaria?',rationale:'Si attiva con un segnale sociale primario; le dimensioni economica, territoriale e digitale amplificano la priorità.',cautions:['I13 e I14 sono presenti nel catalogo V3.0 e in D1.5, ma la demo non dispone ancora di dati o normalizzazione eseguibile; restano visibili come elementi in attesa.']},
  },
  en:{
    P1:{description:'Structurally insufficient resources and pressure from energy costs, reinforced by arrears and low resilience.',question:'Does the household show structural economic vulnerability?',rationale:'It activates under relative poverty or when insufficient income coincides with a high energy burden or non-payment. I11, I12, I21, I22 and I25 adjust priority.',cautions:['I1 and I2 are related; I2 starts at zero weight to avoid double counting before expert review.','I22 is included as a complementary resilience factor with an initial weight of zero.']},
    P2:{description:'Vulnerability caused mainly by the physical, thermal or technical condition of the dwelling.',question:'Does the household show vulnerability due to housing conditions?',rationale:'It activates when habitability or energy systems indicate risk; consumption and discomfort provide context.',cautions:[]},
    P3:{description:'Involuntary underconsumption that is not explained by an efficient dwelling and coincides with economic constraint.',question:'Does the household show hidden energy poverty?',rationale:'It requires an underconsumption signal, conditions that rule out efficiency as the explanation and an economic constraint. I4 reinforces priority.',cautions:['I8 remains a demo approximation; the reference value must be adjusted for household, dwelling and climate.']},
    P4:{description:'Critical energy needs associated with dependency, reduced mobility, health or electrical equipment.',question:'Does the household show fragility or electricity dependence?',rationale:'It activates when at least one primary fragility signal is present. Low income is not an entry requirement.',cautions:['Continuity of electricity supply requires a specific safeguard in addition to the weighted score.']},
    P5:{description:'Territorial disadvantage or effective barriers to infrastructure, services and protection mechanisms.',question:'Does the household show territorial or access vulnerability?',rationale:'It activates through territorial risk or effective access barriers; support and participation adjust priority.',cautions:['I19 appears in D1.5 and the profile proposal, but is retired in the V3.0 catalogue. It is retained temporarily for traceability until a replacement is agreed.']},
    P6:{description:'Weak social support, community integration and effective ability to participate or access assistance.',question:'Does the household show socio-community vulnerability?',rationale:'It activates through a primary social signal; economic, territorial and digital dimensions amplify priority.',cautions:['I13 and I14 appear in the V3.0 catalogue and D1.5, but the demo does not yet have executable data or normalisation; they remain visible as pending.']},
  },
};

let currentLanguage = typeof localStorage !== 'undefined' ? (localStorage.getItem('sociarem_language') || 'es') : 'es';
if (!I18N_MESSAGES[currentLanguage]) currentLanguage = 'es';

function tr(key, fallback = '') { return I18N_MESSAGES[currentLanguage]?.[key] ?? I18N_MESSAGES.es[key] ?? fallback ?? key; }

function setLanguage(language) {
  if (!I18N_MESSAGES[language]) return;
  currentLanguage = language;
  if (typeof localStorage !== 'undefined') localStorage.setItem('sociarem_language', language);
  if (typeof document !== 'undefined') {
    document.documentElement.lang = language;
    document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = tr(element.dataset.i18n, element.textContent); });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = tr(element.dataset.i18nPlaceholder, element.placeholder); });
    document.querySelectorAll('.language-select').forEach(element => { element.value = language; });
  }
}

function translatedProfileField(profileId, field, fallback) { return tr(`profiles.${profileId}.${field}`, fallback); }
function translatedWorkflowField(stage, field) { return tr(`workflow.${stage.id}.${field}`, stage[field]); }
function translatedIndicatorName(indicatorId, fallback = indicatorId) { return I18N_INDICATORS[currentLanguage]?.[indicatorId]?.[0] || I18N_INDICATORS.es[indicatorId]?.[0] || fallback; }
function translatedIndicatorCriterion(indicatorId, thresholds = {}, fallback = '') {
  const template = I18N_INDICATORS[currentLanguage]?.[indicatorId]?.[1] || I18N_INDICATORS.es[indicatorId]?.[1] || fallback;
  return String(template).replace(/\{([^}]+)\}/g, (_match,key) => thresholds[key] ?? `{${key}}`);
}
function translatedProfileContent(profileId, field, fallback) { return I18N_PROFILE_CONTENT[currentLanguage]?.[profileId]?.[field] ?? fallback; }
function translatedMethodologySource(fallback) {
  if (currentLanguage === 'it') return 'D1.5 v2, sezioni 4.2.1–4.2.6 e tabella 39; proposta verificata rispetto a Energy Vulnerability Profiles v1.1.';
  if (currentLanguage === 'en') return 'D1.5 v2, sections 4.2.1–4.2.6 and Table 39; proposal cross-checked against Energy Vulnerability Profiles v1.1.';
  return fallback;
}
function translatedLifecycleStatus(status) {
  const labels = {
    es:{APPROVED:'PUBLICADO',REVIEW:'EN REVISIÓN',DRAFT:'BORRADOR'},
    it:{APPROVED:'PUBBLICATO',REVIEW:'IN REVISIONE',DRAFT:'BOZZA'},
    en:{APPROVED:'PUBLISHED',REVIEW:'IN REVIEW',DRAFT:'DRAFT'},
  };
  return labels[currentLanguage]?.[status] || status;
}
function translatedMethodStatus(status) {
  const labels = {
    es:{PRELIMINAR:'PRELIMINAR','PESOS INICIALES DE LA DEMO':'PESOS INICIALES DE LA DEMO'},
    it:{PRELIMINAR:'PRELIMINARE','PESOS INICIALES DE LA DEMO':'PESI INIZIALI DELLA DEMO'},
    en:{PRELIMINAR:'PRELIMINARY','PESOS INICIALES DE LA DEMO':'INITIAL DEMO WEIGHTS'},
  };
  return labels[currentLanguage]?.[status] || status;
}
function translatedHouseholdName(name) {
  const match = /^Hogar\s+(\d+)$/i.exec(String(name));
  if (!match) return name;
  if (currentLanguage === 'it') return `Nucleo ${match[1]}`;
  if (currentLanguage === 'en') return `Household ${match[1]}`;
  return name;
}
