'use strict';

const I18N_MESSAGES = {
  es:{
    'language.label':'Idioma','language.es':'Español','language.it':'Italiano','language.en':'English','common.phase':'FASE',
    'login.subtitle':'Piloto Messina · PoC de vulnerabilidad energética','login.demo':'Entorno de demostración','login.synthetic':'Datos sintéticos · sin autenticación real','login.user':'Evaluador','login.userPlaceholder':'Nombre o código de evaluador','login.role':'Rol de demostración','login.password':'Contraseña','login.passwordPlaceholder':'Contraseña de acceso','login.enter':'Entrar →',
    'role.methodology':'Diseño metodológico','role.expert':'Persona experta','role.facilitator':'Facilitación del consenso','role.observer':'Observación y auditoría',
    'top.activeProfile':'Perfil activo:','top.user':'Usuario:','top.change':'Cambiar','top.reference':'Mostrar etiquetas de referencia',
    'workflow.profile-builder.short':'Perfiles','workflow.profile-builder.title':'Construcción de perfiles','workflow.profile-builder.state':'Prototipo disponible','workflow.profile-builder.description':'Combinar indicadores en perfiles, definir su activación y publicar las variables que ponderarán los expertos.',
    'workflow.expert-evaluation.short':'Expertos','workflow.expert-evaluation.title':'Evaluación experta individual','workflow.expert-evaluation.state':'Funcional',
    'workflow.expert-consensus.short':'Consenso','workflow.expert-consensus.title':'Consenso entre personas expertas','workflow.expert-consensus.state':'Prototipo disponible',
    'workflow.community-input.short':'Usuarios','workflow.community-input.title':'Preferencias de participantes','workflow.community-input.state':'Roadmap',
    'workflow.community-consensus.short':'Asamblea','workflow.community-consensus.title':'Consenso comunitario','workflow.community-consensus.state':'Roadmap',
    'workflow.benefits-expert.short':'Beneficios','workflow.benefits-expert.title':'Criterios de reparto expertos','workflow.benefits-expert.state':'Roadmap',
    'workflow.benefits-community.short':'Validación','workflow.benefits-community.title':'Validación del reparto','workflow.benefits-community.state':'Roadmap',
    'builder.title':'Construcción de perfiles','builder.subtitle':'Indicadores ya calculados → activación → perfil → ponderación experta','builder.design':'Diseño del perfil','builder.method':'Información metodológica','builder.methodHint':'Fuentes, versión, cautelas y trazabilidad se consultan aquí sin ocupar el espacio de edición.','builder.identity':'1 · Identidad','builder.name':'Nombre','builder.short':'Nombre corto','builder.color':'Color','builder.question':'Pregunta experta','builder.description':'Descripción','builder.composition':'2 · Composición','builder.primary':'Indicadores primarios','builder.secondary':'Indicadores secundarios','builder.pending':'Pendientes','builder.activation':'3 · Regla activadora','builder.activationHelp':'Cada condición devuelve TRUE cuando el indicador cumple su propio criterio. Aquí decides cómo combinar esas condiciones.','builder.trueCondition':'cumple su criterio → TRUE','builder.addCondition':'＋ Añadir condición','builder.replaceCondition':'Cambiar indicador','builder.reading':'Lectura','builder.variables':'4 · Variables que ponderarán los expertos','builder.weightsHint':'El porcentaje mostrado es solo el punto de partida; se modifica en la fase experta.','builder.addVariable':'＋ Añadir variable','builder.initial':'inicial','builder.remove':'Quitar','builder.preview':'5 · Vista previa','builder.previewHint':'Activación y score con hogares sintéticos','builder.active':'ACTIVO','builder.inactive':'No activo','builder.validation':'6 · Validación y publicación','builder.restore':'Restaurar guardado','builder.export':'↓ Exportar JSON','builder.import':'↑ Importar JSON','builder.saveDraft':'Guardar DRAFT','builder.review':'Enviar a REVIEW','builder.publish':'Publicar para expertos','builder.newProfile':'＋ Nuevo perfil','builder.viewOnly':'Vista de consulta. Usa el rol Diseño metodológico para editar.','builder.valid':'Regla activadora y priorización válidas.','builder.source':'Fuente metodológica','builder.activationRationale':'Justificación de la activación','builder.cautions':'Cautelas y decisiones pendientes','builder.version':'Estado metodológico','builder.profiles':'perfiles','builder.published':'publicados','builder.primaryRole':'Primario','builder.secondaryRole':'Secundario','builder.addedRole':'Añadido',
    'profiles.P1.name':'Vulnerabilidad económica estructural','profiles.P1.short':'Económica','profiles.P2.name':'Vulnerabilidad por condiciones de la vivienda','profiles.P2.short':'Vivienda','profiles.P3.name':'Pobreza energética oculta','profiles.P3.short':'P. oculta','profiles.P4.name':'Fragilidad del hogar y dependencia eléctrica','profiles.P4.short':'Fragilidad','profiles.P5.name':'Vulnerabilidad territorial y de acceso','profiles.P5.short':'Territorial','profiles.P6.name':'Vulnerabilidad socio-comunitaria','profiles.P6.short':'Socio-com.',
  },
  it:{
    'language.label':'Lingua','language.es':'Español','language.it':'Italiano','language.en':'English','common.phase':'FASE',
    'login.subtitle':'Pilota Messina · PoC sulla vulnerabilità energetica','login.demo':'Ambiente dimostrativo','login.synthetic':'Dati sintetici · nessuna autenticazione reale','login.user':'Valutatore','login.userPlaceholder':'Nome o codice del valutatore','login.role':'Ruolo dimostrativo','login.password':'Password','login.passwordPlaceholder':'Password di accesso','login.enter':'Accedi →',
    'role.methodology':'Progettazione metodologica','role.expert':'Persona esperta','role.facilitator':'Facilitazione del consenso','role.observer':'Osservazione e audit',
    'top.activeProfile':'Profilo attivo:','top.user':'Utente:','top.change':'Cambia','top.reference':'Mostra etichette di riferimento',
    'workflow.profile-builder.short':'Profili','workflow.profile-builder.title':'Costruzione dei profili','workflow.profile-builder.state':'Prototipo disponibile','workflow.profile-builder.description':'Combinare gli indicatori nei profili, definirne l’attivazione e pubblicare le variabili che gli esperti pondereranno.',
    'workflow.expert-evaluation.short':'Esperti','workflow.expert-evaluation.title':'Valutazione individuale degli esperti','workflow.expert-evaluation.state':'Funzionale',
    'workflow.expert-consensus.short':'Consenso','workflow.expert-consensus.title':'Consenso tra esperti','workflow.expert-consensus.state':'Prototipo disponibile',
    'workflow.community-input.short':'Utenti','workflow.community-input.title':'Preferenze dei partecipanti','workflow.community-input.state':'Roadmap',
    'workflow.community-consensus.short':'Assemblea','workflow.community-consensus.title':'Consenso comunitario','workflow.community-consensus.state':'Roadmap',
    'workflow.benefits-expert.short':'Benefici','workflow.benefits-expert.title':'Criteri esperti di distribuzione','workflow.benefits-expert.state':'Roadmap',
    'workflow.benefits-community.short':'Convalida','workflow.benefits-community.title':'Convalida della distribuzione','workflow.benefits-community.state':'Roadmap',
    'builder.title':'Costruzione dei profili','builder.subtitle':'Indicatori calcolati → attivazione → profilo → ponderazione esperta','builder.design':'Progettazione del profilo','builder.method':'Informazioni metodologiche','builder.methodHint':'Fonti, versione, cautele e tracciabilità sono consultabili qui senza occupare lo spazio di modifica.','builder.identity':'1 · Identità','builder.name':'Nome','builder.short':'Nome breve','builder.color':'Colore','builder.question':'Domanda per gli esperti','builder.description':'Descrizione','builder.composition':'2 · Composizione','builder.primary':'Indicatori primari','builder.secondary':'Indicatori secondari','builder.pending':'In attesa','builder.activation':'3 · Regola di attivazione','builder.activationHelp':'Ogni condizione restituisce TRUE quando l’indicatore soddisfa il proprio criterio. Qui si decide come combinare le condizioni.','builder.trueCondition':'soddisfa il criterio → TRUE','builder.addCondition':'＋ Aggiungi condizione','builder.replaceCondition':'Cambia indicatore','builder.reading':'Lettura','builder.variables':'4 · Variabili ponderate dagli esperti','builder.weightsHint':'La percentuale mostrata è solo il punto di partenza; viene modificata nella fase esperta.','builder.addVariable':'＋ Aggiungi variabile','builder.initial':'iniziale','builder.remove':'Rimuovi','builder.preview':'5 · Anteprima','builder.previewHint':'Attivazione e punteggio con famiglie sintetiche','builder.active':'ATTIVO','builder.inactive':'Non attivo','builder.validation':'6 · Validazione e pubblicazione','builder.restore':'Ripristina salvato','builder.export':'↓ Esporta JSON','builder.import':'↑ Importa JSON','builder.saveDraft':'Salva DRAFT','builder.review':'Invia a REVIEW','builder.publish':'Pubblica per gli esperti','builder.newProfile':'＋ Nuovo profilo','builder.viewOnly':'Vista di sola lettura. Usa il ruolo Progettazione metodologica per modificare.','builder.valid':'Regola di attivazione e prioritizzazione valide.','builder.source':'Fonte metodologica','builder.activationRationale':'Motivazione dell’attivazione','builder.cautions':'Cautele e decisioni aperte','builder.version':'Stato metodologico','builder.profiles':'profili','builder.published':'pubblicati','builder.primaryRole':'Primario','builder.secondaryRole':'Secondario','builder.addedRole':'Aggiunto',
    'profiles.P1.name':'Vulnerabilità economica strutturale','profiles.P1.short':'Economica','profiles.P2.name':'Vulnerabilità dovuta alle condizioni abitative','profiles.P2.short':'Abitazione','profiles.P3.name':'Povertà energetica nascosta','profiles.P3.short':'Povertà nascosta','profiles.P4.name':'Fragilità familiare e dipendenza elettrica','profiles.P4.short':'Fragilità','profiles.P5.name':'Vulnerabilità territoriale e di accesso','profiles.P5.short':'Territoriale','profiles.P6.name':'Vulnerabilità socio-comunitaria','profiles.P6.short':'Socio-com.',
  },
  en:{
    'language.label':'Language','language.es':'Español','language.it':'Italiano','language.en':'English','common.phase':'PHASE',
    'login.subtitle':'Messina pilot · Energy vulnerability PoC','login.demo':'Demonstration environment','login.synthetic':'Synthetic data · no real authentication','login.user':'Evaluator','login.userPlaceholder':'Evaluator name or code','login.role':'Demo role','login.password':'Password','login.passwordPlaceholder':'Access password','login.enter':'Enter →',
    'role.methodology':'Methodology design','role.expert':'Expert','role.facilitator':'Consensus facilitation','role.observer':'Observation and audit',
    'top.activeProfile':'Active profile:','top.user':'User:','top.change':'Change','top.reference':'Show reference labels',
    'workflow.profile-builder.short':'Profiles','workflow.profile-builder.title':'Profile construction','workflow.profile-builder.state':'Prototype available','workflow.profile-builder.description':'Combine indicators into profiles, define activation and publish the variables experts will weight.',
    'workflow.expert-evaluation.short':'Experts','workflow.expert-evaluation.title':'Individual expert assessment','workflow.expert-evaluation.state':'Functional',
    'workflow.expert-consensus.short':'Consensus','workflow.expert-consensus.title':'Expert consensus','workflow.expert-consensus.state':'Prototype available',
    'workflow.community-input.short':'Users','workflow.community-input.title':'Participant preferences','workflow.community-input.state':'Roadmap',
    'workflow.community-consensus.short':'Assembly','workflow.community-consensus.title':'Community consensus','workflow.community-consensus.state':'Roadmap',
    'workflow.benefits-expert.short':'Benefits','workflow.benefits-expert.title':'Expert allocation criteria','workflow.benefits-expert.state':'Roadmap',
    'workflow.benefits-community.short':'Validation','workflow.benefits-community.title':'Allocation validation','workflow.benefits-community.state':'Roadmap',
    'builder.title':'Profile construction','builder.subtitle':'Calculated indicators → activation → profile → expert weighting','builder.design':'Profile design','builder.method':'Methodology information','builder.methodHint':'Sources, version, cautions and traceability live here without taking up editing space.','builder.identity':'1 · Identity','builder.name':'Name','builder.short':'Short name','builder.color':'Colour','builder.question':'Expert question','builder.description':'Description','builder.composition':'2 · Composition','builder.primary':'Primary indicators','builder.secondary':'Secondary indicators','builder.pending':'Pending','builder.activation':'3 · Activation rule','builder.activationHelp':'Each condition returns TRUE when the indicator meets its own criterion. Here you decide how to combine those conditions.','builder.trueCondition':'meets its criterion → TRUE','builder.addCondition':'＋ Add condition','builder.replaceCondition':'Change indicator','builder.reading':'Reading','builder.variables':'4 · Variables weighted by experts','builder.weightsHint':'The displayed percentage is only the starting point; it is changed during the expert phase.','builder.addVariable':'＋ Add variable','builder.initial':'initial','builder.remove':'Remove','builder.preview':'5 · Preview','builder.previewHint':'Activation and score using synthetic households','builder.active':'ACTIVE','builder.inactive':'Inactive','builder.validation':'6 · Validation and publishing','builder.restore':'Restore saved','builder.export':'↓ Export JSON','builder.import':'↑ Import JSON','builder.saveDraft':'Save DRAFT','builder.review':'Send to REVIEW','builder.publish':'Publish for experts','builder.newProfile':'＋ New profile','builder.viewOnly':'Read-only view. Use the Methodology design role to edit.','builder.valid':'Activation rule and prioritisation are valid.','builder.source':'Methodology source','builder.activationRationale':'Activation rationale','builder.cautions':'Cautions and open decisions','builder.version':'Methodology status','builder.profiles':'profiles','builder.published':'published','builder.primaryRole':'Primary','builder.secondaryRole':'Secondary','builder.addedRole':'Added',
    'profiles.P1.name':'Structural economic vulnerability','profiles.P1.short':'Economic','profiles.P2.name':'Housing-condition vulnerability','profiles.P2.short':'Housing','profiles.P3.name':'Hidden energy poverty','profiles.P3.short':'Hidden poverty','profiles.P4.name':'Household fragility and electricity dependence','profiles.P4.short':'Fragility','profiles.P5.name':'Territorial and access vulnerability','profiles.P5.short':'Territorial','profiles.P6.name':'Socio-community vulnerability','profiles.P6.short':'Socio-community',
  },
};

let currentLanguage = typeof localStorage !== 'undefined' ? (localStorage.getItem('sociarem_language') || 'es') : 'es';
if (!I18N_MESSAGES[currentLanguage]) currentLanguage = 'es';

function tr(key, fallback = '') { return I18N_MESSAGES[currentLanguage]?.[key] ?? I18N_MESSAGES.es[key] ?? fallback ?? key; }

function setLanguage(language) {
  if (!I18N_MESSAGES[language]) return;
  currentLanguage = language;
  if (typeof localStorage !== 'undefined') localStorage.setItem('sociarem_language', language);
  if (typeof document !== 'undefined') {
    document.documentElement.lang = language;
    document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = tr(element.dataset.i18n, element.textContent); });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = tr(element.dataset.i18nPlaceholder, element.placeholder); });
    document.querySelectorAll('.language-select').forEach(element => { element.value = language; });
  }
}

function translatedProfileField(profileId, field, fallback) { return tr(`profiles.${profileId}.${field}`, fallback); }
function translatedWorkflowField(stage, field) { return tr(`workflow.${stage.id}.${field}`, stage[field]); }
